<script setup lang="ts">
import { z } from 'zod'
import type { FieldType, FormField } from '~/composables/formFieldsService'
definePageMeta({ layout: 'admin' })
const authStore = useAuthStore(); const canEdit = computed(()=>['ADMIN','MARKETING'].includes(authStore.user?.role||''))
const route=useRoute(); const service=useFormFieldsService(); const formId=String(route.params.id)
const fields=ref<FormField[]>([]); const selected=ref<FormField | null>(null); const errorMessage=ref(''); const isLoading=ref(false)
const config=reactive({ label:'', name:'', type:'TEXT' as FieldType, placeholder:'', isRequired:false, optionsText:'', order:0 })
const schema=z.object({label:z.string().min(2),name:z.string().min(2),type:z.enum(['TEXT','EMAIL','PHONE','SELECT','CHECKBOX','RADIO','TEXTAREA','DATE','HIDDEN']),placeholder:z.string().optional(),isRequired:z.boolean(),order:z.number().int().min(0)})
const slugify=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[^\w\s-]/g,'').trim().replace(/\s+/g,'-')
watch(()=>config.label,(val)=>{ if(!selected.value) config.name=slugify(val) })
const load=async()=>{ isLoading.value=true; try{ fields.value=(await service.list(formId)).sort((a,b)=>a.order-b.order)}catch(e){errorMessage.value=getFriendlyErrorMessage(e)}finally{isLoading.value=false}}
const toOptions=()=>config.optionsText.split('\n').map((v)=>v.trim()).filter(Boolean)
const save=async()=>{ if(!canEdit.value) return; const parsed=schema.safeParse({...config,name:slugify(config.name)}); if(!parsed.success){errorMessage.value=parsed.error.issues[0].message; return}; const payload={...parsed.data,name:slugify(parsed.data.name),options:['SELECT','RADIO','CHECKBOX'].includes(parsed.data.type)?toOptions():undefined}; if(selected.value){await service.update(formId,selected.value.id,payload)} else {await service.create(formId,payload)}; selected.value=null; Object.assign(config,{ label:'', name:'', type:'TEXT', placeholder:'', isRequired:false, optionsText:'', order:fields.value.length}); await load() }
const editField=(f:FormField)=>{ selected.value=f; Object.assign(config,{...f,optionsText:(f.options||[]).join('\n')}) }
const toggleActive=async(f:FormField)=>{ if(!canEdit.value) return; if(f.isActive) await service.deactivate(formId,f.id); else await service.activate(formId,f.id); await load() }
const move=async(f:FormField,dir:number)=>{ if(!canEdit.value) return; const idx=fields.value.findIndex(i=>i.id===f.id); const next=idx+dir; if(next<0||next>=fields.value.length) return; [fields.value[idx],fields.value[next]]=[fields.value[next],fields.value[idx]]; await service.reorder(formId,fields.value.map((item,i)=>({id:item.id,order:i}))); await load() }
onMounted(load)
</script>
<template><div class="space-y-4"><h2 class="text-2xl font-semibold">Construtor de campos</h2><BaseAlert v-if="errorMessage" type="error" :message="errorMessage"/><div class="grid gap-4 lg:grid-cols-2"><BaseCard class="space-y-2"><h3 class="font-semibold">{{ selected ? 'Editar campo' : 'Novo campo' }}</h3><BaseInput v-model="config.label" label="Label"/><BaseInput v-model="config.name" label="Name"/><BaseSelect v-model="config.type" label="Type" :options="['TEXT','EMAIL','PHONE','SELECT','CHECKBOX','RADIO','TEXTAREA','DATE','HIDDEN'].map((t)=>({label:t,value:t}))"/><BaseInput v-model="config.placeholder" label="Placeholder"/><BaseInput v-model="config.order" type="number" label="Order"/><BaseCheckbox v-model="config.isRequired" label="Required"/><BaseTextarea v-if="['SELECT','RADIO','CHECKBOX'].includes(config.type)" v-model="config.optionsText" label="Options (one per line)"/><BaseButton v-if="canEdit" label="Salvar campo" @click="save"/></BaseCard><BaseCard><h3 class="mb-2 font-semibold">Preview público</h3><div class="space-y-2"><div v-for="field in fields.filter((f)=>f.isActive)" :key="field.id"><label class="text-sm">{{ field.label }} <span v-if="field.isRequired">*</span></label><input v-if="['TEXT','EMAIL','PHONE','DATE','HIDDEN'].includes(field.type)" class="w-full rounded border p-2" :placeholder="field.placeholder"><textarea v-else-if="field.type==='TEXTAREA'" class="w-full rounded border p-2" :placeholder="field.placeholder"/><div v-else class="text-sm text-slate-500">Options: {{ field.options?.join(', ') }}</div></div></div></BaseCard></div><BaseCard><h3 class="mb-2 font-semibold">Campos</h3><BaseTable><thead><tr><th class="p-2">Label</th><th>Type</th><th>Order</th><th>Status</th><th>Ações</th></tr></thead><tbody><tr v-for="field in fields" :key="field.id" class="border-b"><td class="p-2">{{field.label}}</td><td>{{field.type}}</td><td>{{field.order}}</td><td><BaseBadge :variant="field.isActive ? 'success':'danger'">{{ field.isActive ? 'ACTIVE':'INACTIVE' }}</BaseBadge></td><td class="space-x-2"><BaseButton v-if="canEdit" variant="secondary" label="Editar" @click="editField(field)"/><BaseButton v-if="canEdit" :variant="field.isActive?'danger':'success'" :label="field.isActive ? 'Desativar' : 'Ativar'" @click="toggleActive(field)"/><BaseButton v-if="canEdit" variant="secondary" label="↑" @click="move(field,-1)"/><BaseButton v-if="canEdit" variant="secondary" label="↓" @click="move(field,1)"/></td></tr></tbody></BaseTable></BaseCard></div></template>
