<script setup lang="ts">
import type { LeadStatus } from '~/composables/leadsService'
definePageMeta({ layout: 'admin' })
const authStore = useAuthStore(); const leadsService = useLeadsService()
const { can } = usePermissions()
const canExport = computed(()=>can('exportLeads'))
const canResend = computed(()=>can('resendRubeus'))
const filters = reactive({ formId:'', unitId:'', gradeId:'', status:'', rubeusStatus:'', startDate:'', endDate:'', search:'', page:1, limit:20 })
const leads=ref<any[]>([]); const total=ref(0); const isLoading=ref(false); const errorMessage=ref('')
const load=async()=>{ isLoading.value=true; errorMessage.value=''; try{ const r=await leadsService.list(filters); leads.value=r.data; total.value=r.total }catch(e){ errorMessage.value=getFriendlyErrorMessage(e) }finally{ isLoading.value=false } }
const totalPages=computed(()=>Math.max(1,Math.ceil(total.value/filters.limit)))
watch(()=>filters.page,load)
const updateStatus=async(id:string,status:LeadStatus)=>{ await leadsService.updateStatus(id,status); await load() }
const resend=async(id:string)=>{ if(!canResend.value) return; await leadsService.resendRubeus(id); await load() }
const download=(content:string|Blob, fileName:string, mime='text/plain')=>{ const blob = content instanceof Blob ? content : new Blob([content], { type: mime }); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=fileName; a.click(); URL.revokeObjectURL(url) }
const exportLoading = ref(false)
const exportCsv=async()=>{ if(!canExport.value) return; exportLoading.value=true; try{ const data=await leadsService.exportCsv(filters); download(data,'leads.csv','text/csv') } catch(e){ errorMessage.value=getFriendlyErrorMessage(e) } finally{ exportLoading.value=false } }
const exportPdf=async()=>{ if(!canExport.value) return; exportLoading.value=true; try{ const data=await leadsService.exportPdf(filters); download(data,'leads.pdf','application/pdf') } catch(e){ errorMessage.value=getFriendlyErrorMessage(e) } finally{ exportLoading.value=false } }
onMounted(load)
</script>
<template><div class="space-y-4"><div class="flex items-center justify-between"><h2 class="text-2xl font-semibold">Leads</h2><div class="flex gap-2"><BaseButton v-if="canExport" :loading="exportLoading" variant="secondary" label="Exportar CSV" @click="exportCsv"/><BaseButton v-if="canExport" :loading="exportLoading" variant="secondary" label="Exportar PDF" @click="exportPdf"/></div></div><BaseCard><div class="grid gap-3 md:grid-cols-4"><BaseInput v-model="filters.formId" label="Formulário"/><BaseInput v-model="filters.unitId" label="Unidade"/><BaseInput v-model="filters.gradeId" label="Série"/><BaseSelect v-model="filters.status" label="Status" :options="[{label:'Todos',value:''},{label:'SCHEDULED',value:'SCHEDULED'},{label:'ATTENDED',value:'ATTENDED'},{label:'NO_SHOW',value:'NO_SHOW'},{label:'RESCHEDULED',value:'RESCHEDULED'},{label:'CANCELED',value:'CANCELED'}]"/><BaseInput v-model="filters.rubeusStatus" label="Status Rubeus"/><BaseInput v-model="filters.startDate" type="date" label="Período inicial"/><BaseInput v-model="filters.endDate" type="date" label="Período final"/><BaseInput v-model="filters.search" label="Busca" placeholder="Nome, email ou telefone"/></div><div class="mt-3"><BaseButton :loading="isLoading" label="Aplicar filtros" @click="filters.page=1; load()"/></div></BaseCard><BaseAlert v-if="errorMessage" type="error" :message="errorMessage"/><div v-else-if="isLoading" class="flex items-center gap-2"><BaseLoading/> Loading leads...</div><BaseTable v-else-if="leads.length"><thead><tr class="text-left"><th class="p-2">Nome</th><th>Email</th><th>Telefone</th><th>Formulário</th><th>Unidade</th><th>Série</th><th>Data</th><th>Horário</th><th>Status</th><th>Rubeus</th><th>Criado em</th><th>Ações</th></tr></thead><tbody><tr v-for="lead in leads" :key="lead.id" class="border-b"><td class="p-2">{{lead.name}}</td><td>{{lead.email}}</td><td>{{lead.phone}}</td><td>{{lead.formName}}</td><td>{{lead.unitName}}</td><td>{{lead.gradeName}}</td><td>{{lead.date}}</td><td>{{lead.time}}</td><td><BaseSelect :model-value="lead.status" :options="['SCHEDULED','ATTENDED','NO_SHOW','RESCHEDULED','CANCELED'].map((s)=>({label:s,value:s}))" @update:model-value="updateStatus(lead.id, $event as LeadStatus)"/></td><td><BaseBadge :variant="lead.rubeusStatus==='ERROR' ? 'danger':'neutral'">{{lead.rubeusStatus || '-'}}</BaseBadge></td><td>{{lead.createdAt}}</td><td class="space-x-2"><NuxtLink :to="`/admin/leads/${lead.id}`"><BaseButton variant="secondary" label="Detalhes"/></NuxtLink><BaseButton v-if="canResend" variant="secondary" label="Reenviar" @click="resend(lead.id)"/></td></tr></tbody></BaseTable><EmptyState v-else title="Sem leads" description="Nenhum lead encontrado."/><BasePagination :page="filters.page" :total-pages="totalPages" @update:page="filters.page = $event"/></div></template>
